export const CHAKRAS = [
  {
    numero: 1,
    nombre: 'Muladhara',
    nombreEspanol: 'Chakra Raíz',
    simbolo: '🔴',
    color: '#ef4444',
    ubicacion: 'Base de la columna',
    keywords: 'Seguridad · Supervivencia · Enraizamiento · Cuerpo',
    elemento: 'Tierra',
    descripcion: 'El chakra raíz es la base de todo el sistema energético. Gobierna nuestra sensación de seguridad, nuestras necesidades básicas y nuestra conexión con el mundo físico.',
    equilibrado: 'Te sientes seguro, enraizado, con los pies en la tierra. Confías en que tus necesidades básicas serán cubiertas.',
    desequilibrado: 'Miedo, ansiedad, inseguridad económica, desconexión del cuerpo, problemas de salud en las piernas o columna.',
    practica: 'Camina descalzo sobre la tierra. Come alimentos rojos y nutritivos. Practica ejercicio físico regular. Repite: "Estoy seguro. Estoy enraizado."',
  },
  {
    numero: 2,
    nombre: 'Svadhisthana',
    nombreEspanol: 'Chakra Sacro',
    simbolo: '🟠',
    color: '#f97316',
    ubicacion: 'Bajo vientre',
    keywords: 'Creatividad · Placer · Emoción · Sexualidad',
    elemento: 'Agua',
    descripcion: 'El chakra sacro gobierna la creatividad, el placer, las emociones y la sexualidad. Es el centro del flujo vital y de la capacidad de sentir y crear.',
    equilibrado: 'Fluyes con la vida, disfrutas el placer sin culpa, eres creativo, tienes relaciones saludables con límites claros.',
    desequilibrado: 'Bloqueo creativo, culpa alrededor del placer, dificultades en relaciones íntimas, rigidez emocional o exceso emocional.',
    practica: 'Baila libremente. Practica actividades creativas sin juzgar el resultado. Conecta con el agua — baños, ríos, lluvia. Repite: "Fluyo con la vida."',
  },
  {
    numero: 3,
    nombre: 'Manipura',
    nombreEspanol: 'Chakra del Plexo Solar',
    simbolo: '🟡',
    color: '#eab308',
    ubicacion: 'Plexo solar',
    keywords: 'Poder personal · Voluntad · Autoestima · Acción',
    elemento: 'Fuego',
    descripcion: 'El chakra del plexo solar es el centro del poder personal, la voluntad y la autoestima. Desde aquí actuamos en el mundo y afirmamos quiénes somos.',
    equilibrado: 'Tienes confianza en ti mismo, puedes establecer límites, tomas decisiones con claridad, te sientes motivado y con propósito.',
    desequilibrado: 'Baja autoestima, dificultad para tomar decisiones, necesidad de control excesivo, problemas digestivos, falta de motivación.',
    practica: 'Exponte al sol — literalmente. Practica posturas de poder. Haz algo que te dé miedo y hazlo igualmente. Repite: "Soy capaz. Tengo poder."',
  },
  {
    numero: 4,
    nombre: 'Anahata',
    nombreEspanol: 'Chakra del Corazón',
    simbolo: '💚',
    color: '#22c55e',
    ubicacion: 'Centro del pecho',
    keywords: 'Amor · Compasión · Perdón · Conexión',
    elemento: 'Aire',
    descripcion: 'El chakra del corazón es el centro del amor — hacia uno mismo y hacia los demás. Es el puente entre los chakras inferiores (materia) y superiores (espíritu).',
    equilibrado: 'Amas y recibes amor con facilidad, te tratas con compasión, puedes perdonar, sientes conexión con los demás y con la vida.',
    desequilibrado: 'Dificultad para amar o recibir amor, resentimiento, miedo al abandono, codependencia o aislamiento, problemas respiratorios o cardíacos.',
    practica: 'Practica la autocompasión activamente. Escribe una carta de perdón — a ti mismo o a alguien. Abraza a alguien. Repite: "Merezco amor. Doy amor libremente."',
  },
  {
    numero: 5,
    nombre: 'Vishuddha',
    nombreEspanol: 'Chakra de la Garganta',
    simbolo: '🔵',
    color: '#3b82f6',
    ubicacion: 'Garganta',
    keywords: 'Comunicación · Verdad · Expresión · Autenticidad',
    elemento: 'Éter',
    descripcion: 'El chakra de la garganta gobierna la comunicación, la verdad y la expresión auténtica. Es el centro desde donde decimos nuestra verdad al mundo.',
    equilibrado: 'Te expresas con claridad y autenticidad, escuchas activamente, dices la verdad con amor, tu vida refleja tus valores.',
    desequilibrado: 'Dificultad para expresarte, miedo a hablar, mentiras o manipulación, voz que se quiebra bajo presión, problemas de tiroides o garganta.',
    practica: 'Canta, aunque sea solo. Escribe en un diario sin censurarte. Di algo verdadero que has estado guardando. Repite: "Mi voz importa. Mi verdad es válida."',
  },
  {
    numero: 6,
    nombre: 'Ajna',
    nombreEspanol: 'Tercer Ojo',
    simbolo: '🟣',
    color: '#8b5cf6',
    ubicacion: 'Entre las cejas',
    keywords: 'Intuición · Visión · Sabiduría · Percepción',
    elemento: 'Luz',
    descripcion: 'El tercer ojo es el centro de la intuición, la visión interior y la sabiduría. Desde aquí percibimos más allá de lo visible y conectamos con nuestra guía interior.',
    equilibrado: 'Confías en tu intuición, tienes claridad de visión, percibes patrones y conexiones ocultas, tus sueños son vívidos y significativos.',
    desequilibrado: 'Confusión, dificultad para tomar decisiones, desconexión de la intuición, exceso de pensamiento racional, dolores de cabeza.',
    practica: 'Medita en silencio. Escribe tus sueños nada más despertar. Practica estar presente sin analizar. Repite: "Confío en mi visión interior."',
  },
  {
    numero: 7,
    nombre: 'Sahasrara',
    nombreEspanol: 'Chakra Corona',
    simbolo: '⚪',
    color: '#c084fc',
    ubicacion: 'Coronilla',
    keywords: 'Conciencia · Conexión divina · Trascendencia · Unidad',
    elemento: 'Conciencia pura',
    descripcion: 'El chakra corona es la puerta hacia la conciencia universal y la conexión con algo más grande que uno mismo. Es el punto de encuentro entre lo humano y lo divino.',
    equilibrado: 'Sientes conexión con el todo, tienes un sentido de propósito mayor, la vida tiene significado, experimentas momentos de gracia y trascendencia.',
    desequilibrado: 'Sensación de desconexión espiritual, nihilismo, falta de propósito, exceso de espiritualidad sin enraizamiento, o materialismo extremo.',
    practica: 'Practica la meditación de conciencia pura. Contempla el cielo nocturno. Practica la gratitud profunda. Repite: "Soy parte del todo. Estoy conectado."',
  },
]

export function getChakraDelDia(): typeof CHAKRAS[0] {
  const hoy = new Date()
  const semilla = hoy.getFullYear() * 10000 + (hoy.getMonth() + 1) * 100 + hoy.getDate()
  return CHAKRAS[semilla % CHAKRAS.length]
}

export function getChakraAleatorio(): typeof CHAKRAS[0] {
  return CHAKRAS[Math.floor(Math.random() * CHAKRAS.length)]
}