export type OduIfa = {
  nombre: string
  yoruba: string
  numero: number
  simbolo: string
  energia: string
  mensaje: string
  consejo: string
  orisha: string
  color: string
}

export const ODU_IFA: OduIfa[] = [
  {
    numero: 1,
    nombre: 'Eji Ogbe',
    yoruba: 'Èjì Ogbè',
    simbolo: '||||||||',
    energia: 'Luz · Destino · Alineación',
    orisha: 'Obatalá',
    color: '#ffffff',
    mensaje: 'Eji Ogbe es el primero y más luminoso de los Odù. Habla de alineación perfecta con el destino, de honestidad como camino y de carácter como fundamento. Lo que tocas ahora está bendecido por la luz del origen.',
    consejo: 'Actúa desde la integridad más profunda. Lo que inicias en este momento tiene el impulso del primer Odù — no lo desperdicies en lo pequeño.',
  },
  {
    numero: 2,
    nombre: 'Oyeku Meji',
    yoruba: 'Òyèkú Méjì',
    simbolo: ':: :: :: ::',
    energia: 'Transformación · Cierre · Renacimiento',
    orisha: 'Oyá',
    color: '#1a1a2e',
    mensaje: 'Oyeku Meji habla de finales que son comienzos. Todo ciclo que termina abre espacio para algo nuevo. La oscuridad que ves no es ausencia de luz — es el vientre donde nace la próxima forma de tu vida.',
    consejo: 'Suelta lo que ya cumplió su función. El miedo al final es el único obstáculo real. Confía en que lo que viene es más grande que lo que dejas ir.',
  },
  {
    numero: 3,
    nombre: 'Iwori Meji',
    yoruba: 'Ìwòrì Méjì',
    simbolo: '| :: | ::',
    energia: 'Visión · Posibilidades reales · Claridad',
    orisha: 'Eshu',
    color: '#6b21a8',
    mensaje: 'Iwori Meji activa la capacidad de ver más allá de lo aparente. No todas las puertas que parecen abiertas lo están — y no todas las cerradas lo están tampoco. Usa la visión interior para distinguir lo real de lo ilusorio.',
    consejo: 'Antes de actuar, observa. Las posibilidades reales no siempre brillan — a veces están justo donde nadie mira.',
  },
  {
    numero: 4,
    nombre: 'Odi Meji',
    yoruba: 'Òdí Méjì',
    simbolo: ':: | :: |',
    energia: 'Manifestación · Sellado · Irreversibilidad',
    orisha: 'Yemayá',
    color: '#1d4ed8',
    mensaje: 'Odi Meji es el sello. Lo que se marca con este Odù se vuelve permanente. Habla de manifestación profunda, de nacimiento y de los actos que no tienen marcha atrás. Lo que hagas ahora quedará.',
    consejo: 'Elige con cuidado — las decisiones de hoy tienen peso de permanencia. Pero no temas: lo que nace bajo Odi tiene raíces que nada puede arrancar.',
  },
  {
    numero: 5,
    nombre: 'Irosun Meji',
    yoruba: 'Ìrosùn Méjì',
    simbolo: '| | :: ::',
    energia: 'Protección · Ori · Sangre vital',
    orisha: 'Shangó',
    color: '#dc2626',
    mensaje: 'Irosun Meji desciende para proteger la cabeza y el destino. Habla de la fuerza vital que fluye por tu ser y de la protección que recibes cuando te alineas con tu propósito más profundo. Tu Ori está activo.',
    consejo: 'Confía en tu instinto de supervivencia. La energía que te protege está activa — pero requiere que tú también te protejas eligiendo bien a quién y qué dejas entrar.',
  },
  {
    numero: 6,
    nombre: 'Owonrin Meji',
    yoruba: 'Òwónrín Méjì',
    simbolo: ':: :: | |',
    energia: 'Cambio súbito · Caos creativo · Sorpresa',
    orisha: 'Eshu',
    color: '#f97316',
    mensaje: 'Owonrin Meji trae el viento del cambio inesperado. Lo que parecía estable puede moverse, y lo que parecía imposible puede aparecer de repente. Este Odù no pide control — pide adaptación.',
    consejo: 'Mantente flexible. El cambio que se acerca no es tu enemigo aunque llegue sin avisar. La creatividad nace exactamente en este tipo de momento.',
  },
  {
    numero: 7,
    nombre: 'Obara Meji',
    yoruba: 'Òbàrà Méjì',
    simbolo: '| :: :: |',
    energia: 'Liderazgo · Nobleza · Victoria',
    orisha: 'Shangó',
    color: '#eab308',
    mensaje: 'Obara Meji es el Odù de la realeza interior. Habla de liderazgo que nace del carácter, no del poder. La victoria que anuncia no se conquista con fuerza sino con dignidad y visión.',
    consejo: 'Lidera desde tu nobleza más auténtica. Los que te rodean necesitan tu dirección — dásela con generosidad, no con ego.',
  },
  {
    numero: 8,
    nombre: 'Okanran Meji',
    yoruba: 'Òkànràn Méjì',
    simbolo: ':: | | ::',
    energia: 'Intensidad · Conflicto · Resolución',
    orisha: 'Shangó',
    color: '#ef4444',
    mensaje: 'Okanran Meji trae la energía del conflicto que purifica. Lo que choca bajo este Odù no es destrucción — es la fricción necesaria para que algo más fuerte emerja. El fuego que ves es transformación.',
    consejo: 'No huyas del conflicto que tiene raíz — afróntalo con claridad. Al otro lado de esta tensión hay una versión más fuerte de lo que estás construyendo.',
  },
  {
    numero: 9,
    nombre: 'Ogunda Meji',
    yoruba: 'Ògúndá Méjì',
    simbolo: '| | | ::',
    energia: 'Apertura de caminos · Trabajo · Hierro',
    orisha: 'Ogún',
    color: '#16a34a',
    mensaje: 'Ogunda Meji abre los caminos que estaban cerrados. El machete de Ogún corta lo que bloquea el paso — con esfuerzo, con trabajo honesto y con la voluntad de seguir aunque cueste. El camino está despejándose.',
    consejo: 'El trabajo que haces ahora abre puertas que otros no pueden abrir. No te detengas ante los obstáculos — son exactamente lo que este Odù vino a cortar.',
  },
  {
    numero: 10,
    nombre: 'Osa Meji',
    yoruba: 'Òsá Méjì',
    simbolo: ':: | :: |',
    energia: 'Movimiento rápido · Huida · Renovación',
    orisha: 'Oyá',
    color: '#7c3aed',
    mensaje: 'Osa Meji trae velocidad y cambio de dirección. Lo que necesita irse, irá rápido. Lo que llega, llega de improviso. Este Odù no da tiempo para dudar — pide que te muevas con la misma velocidad del viento.',
    consejo: 'Prepárate para moverte rápido. Lo que está por cambiar en tu vida cambiará pronto — y si te adelantas al cambio en lugar de resistirlo, saldrás en posición de fuerza.',
  },
  {
    numero: 11,
    nombre: 'Ika Meji',
    yoruba: 'Ìká Méjì',
    simbolo: '| :: | |',
    energia: 'Sabiduría oculta · Secretos · Profundidad',
    orisha: 'Obatalá',
    color: '#0891b2',
    mensaje: 'Ika Meji guarda los secretos de la sabiduría más profunda. Hay cosas que no se ven a simple vista — y ese es exactamente el mensaje de este Odù. La verdad que necesitas no está en la superficie.',
    consejo: 'Busca más hondo. La respuesta que buscas requiere silencio, paciencia y disposición a ver lo que otros no quieren mirar.',
  },
  {
    numero: 12,
    nombre: 'Oturupon Meji',
    yoruba: 'Òtúrúpòn Méjì',
    simbolo: ':: :: | |',
    energia: 'Inversión · Lo oculto se revela · Giro',
    orisha: 'Babalú Ayé',
    color: '#854d0e',
    mensaje: 'Oturupon Meji habla de inversiones y revelaciones. Lo que estaba oculto sale a la luz. Lo que parecía derrotado puede ser exactamente lo que triunfa. Este Odù invita a mirar la situación desde el ángulo opuesto.',
    consejo: 'Cambia de perspectiva antes de tomar una decisión. Lo que ves desde donde estás no es la imagen completa — hay un giro que lo cambia todo.',
  },
  {
    numero: 13,
    nombre: 'Otura Meji',
    yoruba: 'Òtúrá Méjì',
    simbolo: '| | :: |',
    energia: 'Conexión espiritual · Mensajes divinos · Mediación',
    orisha: 'Orula',
    color: '#15803d',
    mensaje: 'Otura Meji abre el canal entre el mundo visible y el invisible. Los mensajes que recibes ahora — en sueños, en coincidencias, en palabras de extraños — son respuestas reales a preguntas que llevas tiempo haciendo.',
    consejo: 'Presta atención a las señales. Lo que el universo te comunica ahora requiere que estés presente y receptivo, no distraído.',
  },
  {
    numero: 14,
    nombre: 'Irete Meji',
    yoruba: 'Ìretè Méjì',
    simbolo: ':: | | |',
    energia: 'Paciencia · Crecimiento lento · Abundancia',
    orisha: 'Oshún',
    color: '#ca8a04',
    mensaje: 'Irete Meji enseña que lo que crece despacio tiene raíces más profundas. La abundancia que anuncia no llega de golpe — se construye con paciencia, cuidado y fe en el proceso aunque los resultados no sean inmediatos.',
    consejo: 'Confía en el tiempo. Lo que estás cultivando requiere más paciencia de la que crees — y la recompensa será proporcional a lo que has sembrado.',
  },
  {
    numero: 15,
    nombre: 'Ose Meji',
    yoruba: 'Òsé Méjì',
    simbolo: '| :: :: ::',
    energia: 'Fertilidad · Multiplicación · Amor',
    orisha: 'Oshún',
    color: '#f59e0b',
    mensaje: 'Ose Meji trae la energía de la multiplicación y el amor. Lo que se da bajo este Odù regresa multiplicado. Las relaciones, los proyectos y las intenciones que nacen ahora tienen el potencial de expandirse más allá de lo imaginado.',
    consejo: 'Da sin miedo a quedarte sin. El amor y la generosidad bajo Ose Meji son semillas que crecen — cuanto más das, más regresa a ti.',
  },
  {
    numero: 16,
    nombre: 'Ofun Meji',
    yoruba: 'Òfún Méjì',
    simbolo: ':: :: :: |',
    energia: 'Misterio · Completitud · Profundidad máxima',
    orisha: 'Obatalá',
    color: '#a855f7',
    mensaje: 'Ofun Meji es el último y más misterioso de los Odù principales. Habla de completitud, de los ciclos que se cierran totalmente y de la sabiduría que solo llega después de haberlo vivido todo. Estás ante un momento de cierre profundo.',
    consejo: 'Honra lo que termina. El ciclo que se cierra bajo Ofun Meji no es un fracaso — es una graduación. Lo que viene después requiere que hayas completado este capítulo con plena conciencia.',
  },
]

export function lanzarOdu(): OduIfa {
  // Simula 4 lanzamientos binarios → número del 1 al 16
  const lanzamientos = Array.from({ length: 4 }, () => Math.random() > 0.5 ? 1 : 0)
  const indice = lanzamientos.reduce((acc, val, i) => acc + val * Math.pow(2, i), 0) % 16
  return ODU_IFA[indice]
}