export const MEDITACIONES = [
  {
    id: 'respiracion',
    nombre: 'Respiración 4-7-8',
    categoria: 'Calma',
    duracion: '5 minutos',
    nivel: 'Principiante',
    descripcion: 'La técnica de respiración más poderosa para calmar el sistema nervioso en minutos.',
    pasos: [
      { texto: 'Siéntate cómodamente con la espalda recta. Cierra los ojos.', duracion: 10 },
      { texto: 'Exhala completamente por la boca con un sonido audible.', duracion: 5 },
      { texto: 'Inhala por la nariz durante 4 tiempos.', duracion: 4 },
      { texto: 'Retén el aire durante 7 tiempos.', duracion: 7 },
      { texto: 'Exhala completamente por la boca durante 8 tiempos.', duracion: 8 },
      { texto: 'Repite este ciclo 4 veces. Observa cómo tu mente se calma.', duracion: 15 },
    ],
    beneficios: ['Calma la ansiedad inmediatamente', 'Activa el sistema parasimpático', 'Mejora la calidad del sueño', 'Reduce la presión arterial'],
    mejorPara: 'Ansiedad · Insomnio · Estrés agudo · Antes de dormir',
    chakra: 'Garganta · Corazón',
  },
  {
    id: 'body-scan',
    nombre: 'Body Scan Espiritual',
    categoria: 'Conexión',
    duracion: '15 minutos',
    nivel: 'Intermedio',
    descripcion: 'Un viaje consciente por tu cuerpo que combina atención plena con percepción energética.',
    pasos: [
      { texto: 'Recuéstate cómodamente. Cierra los ojos. Respira naturalmente.', duracion: 30 },
      { texto: 'Lleva tu atención a los pies. Siente el peso, la temperatura, cualquier sensación.', duracion: 60 },
      { texto: 'Sube lentamente por las piernas, las rodillas, los muslos. Sin juzgar, solo observar.', duracion: 60 },
      { texto: 'Siente el abdomen expandirse y contraerse con cada respiración.', duracion: 45 },
      { texto: 'Explora el pecho. ¿Qué emociones viven aquí hoy?', duracion: 60 },
      { texto: 'Hombros, brazos, manos. Suelta cualquier tensión que encuentres.', duracion: 45 },
      { texto: 'Cuello, cara, coronilla. Deja que toda tensión se disuelva.', duracion: 45 },
      { texto: 'Siente tu cuerpo completo como una unidad de luz y energía.', duracion: 60 },
    ],
    beneficios: ['Conecta mente y cuerpo', 'Libera tensión almacenada', 'Desarrolla interoceptión', 'Facilita la integración emocional'],
    mejorPara: 'Desconexión del cuerpo · Tensión crónica · Trauma · Práctica espiritual',
    chakra: 'Todos los chakras',
  },
  {
    id: 'luna-llena',
    nombre: 'Meditación de Luna Llena',
    categoria: 'Espiritual',
    duracion: '20 minutos',
    nivel: 'Todos los niveles',
    descripcion: 'Aprovecha la energía amplificada de la luna llena para soltar y agradecer.',
    pasos: [
      { texto: 'Si es posible, siéntate bajo o cerca de la luna. Si no, visualízala claramente.', duracion: 30 },
      { texto: 'Respira profundamente 3 veces. Con cada exhala, suelta el día.', duracion: 30 },
      { texto: 'Visualiza la luz plateada de la luna bañando todo tu cuerpo desde la coronilla.', duracion: 60 },
      { texto: 'Trae a la mente algo que has logrado o aprendido en este ciclo lunar.', duracion: 60 },
      { texto: 'Ahora trae algo que estés listo para soltar. No fuerces — deja que emerja.', duracion: 90 },
      { texto: 'Visualiza eso que sueltas disolviéndose en la luz de la luna. Agradece.', duracion: 60 },
      { texto: 'Formula una intención para el próximo ciclo. Siéntela como si ya fuera real.', duracion: 60 },
      { texto: 'Agradece a la luna. Respira 3 veces. Abre los ojos lentamente.', duracion: 30 },
    ],
    beneficios: ['Conecta con los ciclos naturales', 'Facilita el soltar emocional', 'Potencia la manifestación', 'Profundiza la práctica espiritual'],
    mejorPara: 'Luna llena · Cierres de ciclos · Manifestación · Gratitud',
    chakra: 'Corona · Sacro',
  },
  {
    id: 'chakras',
    nombre: 'Activación de Chakras',
    categoria: 'Energía',
    duracion: '25 minutos',
    nivel: 'Intermedio',
    descripcion: 'Recorre y activa los 7 centros energéticos del cuerpo con visualización y respiración.',
    pasos: [
      { texto: 'Siéntate con la columna recta. Cierra los ojos. Respira profundo 3 veces.', duracion: 30 },
      { texto: 'Chakra Raíz: visualiza una luz roja en la base de tu columna. Siente el suelo bajo ti. "Estoy seguro."', duracion: 60 },
      { texto: 'Chakra Sacro: naranja bajo el ombligo. Fluidez, creatividad, placer. "Fluyo con la vida."', duracion: 60 },
      { texto: 'Chakra Plexo Solar: amarillo en el estómago. Tu poder, tu voluntad. "Soy poderoso y capaz."', duracion: 60 },
      { texto: 'Chakra Corazón: verde en el centro del pecho. Amor, compasión. "Amo y soy amado."', duracion: 60 },
      { texto: 'Chakra Garganta: azul. Tu verdad, tu voz. "Hablo mi verdad con claridad."', duracion: 60 },
      { texto: 'Chakra Tercer Ojo: índigo entre las cejas. Intuición, visión. "Confío en mi percepción."', duracion: 60 },
      { texto: 'Chakra Corona: violeta en la coronilla. Conexión divina. "Soy parte del todo."', duracion: 60 },
      { texto: 'Visualiza todos los chakras brillando juntos como un arcoíris de luz. Respira 3 veces.', duracion: 60 },
    ],
    beneficios: ['Equilibra el sistema energético', 'Aumenta la conciencia corporal', 'Profundiza la práctica espiritual', 'Mejora la claridad mental y emocional'],
    mejorPara: 'Práctica espiritual regular · Desequilibrio energético · Despertar espiritual',
    chakra: 'Todos los chakras',
  },
  {
    id: 'gratitud',
    nombre: 'Meditación de Gratitud',
    categoria: 'Bienestar',
    duracion: '10 minutos',
    nivel: 'Principiante',
    descripcion: 'Una práctica simple y poderosa que eleva la vibración y cambia la perspectiva.',
    pasos: [
      { texto: 'Siéntate cómodamente. Cierra los ojos. Coloca la mano en tu corazón.', duracion: 20 },
      { texto: 'Trae a la mente a alguien que amas. Siente el amor en tu pecho expandirse.', duracion: 60 },
      { texto: 'Piensa en algo de tu cuerpo que funciona bien y que das por sentado.', duracion: 45 },
      { texto: 'Recuerda un momento hermoso reciente, por pequeño que sea.', duracion: 45 },
      { texto: 'Piensa en algo difícil que has superado. Agradece la fortaleza que te dio.', duracion: 60 },
      { texto: 'Siente gratitud por este momento exacto — tu respiración, tu conciencia.', duracion: 60 },
      { texto: 'Deja que esa gratitud se expanda por todo tu cuerpo como calor.', duracion: 45 },
      { texto: 'Respira 3 veces. Lleva esta energía contigo al resto del día.', duracion: 20 },
    ],
    beneficios: ['Eleva el estado de ánimo inmediatamente', 'Cambia el patrón mental hacia lo positivo', 'Mejora las relaciones', 'Reduce el estrés'],
    mejorPara: 'Días difíciles · Práctica matutina · Depresión leve · Manifestación',
    chakra: 'Corazón',
  },
]

export function getMeditacionDelDia(): typeof MEDITACIONES[0] {
  const hoy = new Date()
  const semilla = hoy.getFullYear() * 10000 + (hoy.getMonth() + 1) * 100 + hoy.getDate()
  return MEDITACIONES[semilla % MEDITACIONES.length]
}