export const RUNAS = [
  { nombre: 'Fehu', simbolo: 'ᚠ', transliteracion: 'F', keywords: 'Riqueza · Abundancia · Éxito', significado: 'Fehu representa la riqueza móvil, el ganado, los recursos. Habla de prosperidad ganada mediante esfuerzo y la responsabilidad que conlleva la abundancia.', invertida: 'Pérdida material, avaricia, mal uso de los recursos.' },
  { nombre: 'Uruz', simbolo: 'ᚢ', transliteracion: 'U', keywords: 'Fuerza · Vitalidad · Salud', significado: 'Uruz es la fuerza del uro salvaje, la vitalidad primitiva y el poder de manifestación. Habla de energía física y capacidad de superar obstáculos.', invertida: 'Debilidad, enfermedad, oportunidades perdidas.' },
  { nombre: 'Thurisaz', simbolo: 'ᚦ', transliteracion: 'TH', keywords: 'Protección · Fuerza · Cambio', significado: 'Thurisaz es el martillo de Thor, la fuerza protectora y el poder del cambio inevitable. Puede indicar una prueba necesaria.', invertida: 'Peligro, vulnerabilidad, resistencia al cambio necesario.' },
  { nombre: 'Ansuz', simbolo: 'ᚨ', transliteracion: 'A', keywords: 'Comunicación · Sabiduría · Mensaje', significado: 'Ansuz es la runa de Odin, del soplo divino y la palabra. Habla de mensajes importantes, sabiduría recibida y comunicación que transforma.', invertida: 'Malentendidos, engaño, bloqueo en la comunicación.' },
  { nombre: 'Raidho', simbolo: 'ᚱ', transliteracion: 'R', keywords: 'Viaje · Movimiento · Ritmo', significado: 'Raidho es el carro en movimiento, el viaje con propósito. Habla de avanzar en la dirección correcta, de ritmo y de los ciclos naturales.', invertida: 'Interrupción del viaje, movimiento sin propósito, desvíos.' },
  { nombre: 'Kenaz', simbolo: 'ᚲ', transliteracion: 'K', keywords: 'Conocimiento · Luz · Creatividad', significado: 'Kenaz es la antorcha que ilumina la oscuridad. Representa el conocimiento técnico, la creatividad aplicada y la capacidad de ver con claridad.', invertida: 'Ignorancia, pérdida de dirección, creatividad bloqueada.' },
  { nombre: 'Gebo', simbolo: 'ᚷ', transliteracion: 'G', keywords: 'Don · Intercambio · Equilibrio', significado: 'Gebo es el don y la reciprocidad. Todo intercambio crea una relación. Habla de generosidad, de partnerships y del equilibrio entre dar y recibir.', invertida: 'No tiene invertida tradicional. Todo don conlleva responsabilidad.' },
  { nombre: 'Wunjo', simbolo: 'ᚹ', transliteracion: 'W', keywords: 'Alegría · Armonía · Comunidad', significado: 'Wunjo es la alegría de pertenecer, de la comunidad armoniosa. Habla de momentos de felicidad genuina y de conexión con quienes nos rodean.', invertida: 'Tristeza, alienación, armonía rota.' },
  { nombre: 'Hagalaz', simbolo: 'ᚺ', transliteracion: 'H', keywords: 'Disrupción · Transformación · Granizo', significado: 'Hagalaz es el granizo que destruye pero también riega. Representa la disrupción necesaria, el cambio que no podemos controlar pero que prepara el terreno para algo nuevo.', invertida: 'No tiene invertida. La disrupción tiene su propia sabiduría.' },
  { nombre: 'Nauthiz', simbolo: 'ᚾ', transliteracion: 'N', keywords: 'Necesidad · Resistencia · Paciencia', significado: 'Nauthiz es la necesidad y la constricción. Habla de las limitaciones que nos forjan, de la resistencia que construye carácter y del fuego que se enciende frotando.', invertida: 'Impaciencia, resistencia al proceso necesario.' },
  { nombre: 'Isa', simbolo: 'ᛁ', transliteracion: 'I', keywords: 'Quietud · Pausa · Hielo', significado: 'Isa es el hielo: puro, estático, inmóvil. Habla de un período de espera necesaria, de quietud que permite claridad. No es el momento de actuar.', invertida: 'No tiene invertida. La quietud tiene su propio tiempo.' },
  { nombre: 'Jera', simbolo: 'ᛃ', transliteracion: 'J/Y', keywords: 'Ciclos · Cosecha · Recompensa', significado: 'Jera es el año y la cosecha. Lo que sembraste está dando fruto. Habla de ciclos naturales, de recompensa proporcional al esfuerzo y del tiempo correcto.', invertida: 'No tiene invertida. Los ciclos no se pueden apresurar.' },
  { nombre: 'Eihwaz', simbolo: 'ᛇ', transliteracion: 'EI', keywords: 'Eje · Conexión · Resistencia', significado: 'Eihwaz es el tejo, el árbol entre mundos. Representa la conexión entre lo visible y lo invisible, la resistencia y la transformación a través de los umbrales.', invertida: 'No tiene invertida. Es el eje que sostiene.' },
  { nombre: 'Perthro', simbolo: 'ᛈ', transliteracion: 'P', keywords: 'Misterio · Destino · Suerte', significado: 'Perthro es el cubilete de los dados, el misterio del destino. Habla de lo oculto que está por revelarse, de la suerte y de los patrones que no vemos.', invertida: 'Mala suerte, secretos dañinos, destino resistido.' },
  { nombre: 'Algiz', simbolo: 'ᛉ', transliteracion: 'Z', keywords: 'Protección · Defensa · Conexión divina', significado: 'Algiz es el alce y el gesto de protección. Representa la capacidad de protegerse y de conectar con fuerzas superiores. Estás protegido.', invertida: 'Vulnerabilidad, pérdida de protección, desconexión espiritual.' },
  { nombre: 'Sowilo', simbolo: 'ᛋ', transliteracion: 'S', keywords: 'Sol · Éxito · Energía', significado: 'Sowilo es el sol victorioso. Representa el éxito, la energía vital y la capacidad de completar lo que se comenzó. La luz siempre vence a la oscuridad.', invertida: 'No tiene invertida. El sol siempre brilla en algún lugar.' },
  { nombre: 'Tiwaz', simbolo: 'ᛏ', transliteracion: 'T', keywords: 'Justicia · Honor · Sacrificio', significado: 'Tiwaz es Tyr, el dios que sacrificó su mano por el bien común. Habla de justicia, honor, liderazgo y del sacrificio consciente por un bien mayor.', invertida: 'Injusticia, cobardía, traición.' },
  { nombre: 'Berkano', simbolo: 'ᛒ', transliteracion: 'B', keywords: 'Nacimiento · Crecimiento · Fertilidad', significado: 'Berkano es el abedul, el árbol de los nuevos comienzos. Representa el nacimiento, el crecimiento gradual y el cuidado de lo que está emergiendo.', invertida: 'Estancamiento, problemas familiares, crecimiento bloqueado.' },
  { nombre: 'Ehwaz', simbolo: 'ᛖ', transliteracion: 'E', keywords: 'Movimiento · Confianza · Colaboración', significado: 'Ehwaz es el caballo y su jinete: el movimiento que surge de la confianza mutua. Habla de colaboración, de viajes y de la armonía entre dos fuerzas.', invertida: 'Desconfianza, movimiento en falso, falta de colaboración.' },
  { nombre: 'Mannaz', simbolo: 'ᛗ', transliteracion: 'M', keywords: 'Humanidad · Self · Comunidad', significado: 'Mannaz es la humanidad, el ser humano en su plenitud. Habla de la conciencia de uno mismo, de la relación con los demás y de nuestro lugar en la comunidad.', invertida: 'Aislamiento, pérdida de identidad, conflicto interno.' },
  { nombre: 'Laguz', simbolo: 'ᛚ', transliteracion: 'L', keywords: 'Agua · Intuición · Flujo', significado: 'Laguz es el lago y el océano: la intuición profunda, el inconsciente y la capacidad de fluir. Habla de confiar en lo que sientes más allá de lo que ves.', invertida: 'Confusión emocional, ir contra la corriente, intuición ignorada.' },
  { nombre: 'Ingwaz', simbolo: 'ᛜ', transliteracion: 'NG', keywords: 'Potencial · Gestación · Descanso', significado: 'Ingwaz es la semilla en reposo, el potencial que se acumula antes de manifestarse. Habla de un período de gestación necesario antes del gran nacimiento.', invertida: 'No tiene invertida. El potencial siempre está ahí.' },
  { nombre: 'Dagaz', simbolo: 'ᛞ', transliteracion: 'D', keywords: 'Amanecer · Transformación · Claridad', significado: 'Dagaz es el amanecer, el momento de claridad entre la noche y el día. Representa una transformación radical que trae una nueva visión. El punto de inflexión.', invertida: 'No tiene invertida. El amanecer siempre llega.' },
  { nombre: 'Othala', simbolo: 'ᛟ', transliteracion: 'O', keywords: 'Herencia · Hogar · Ancestros', significado: 'Othala es la tierra ancestral, el legado y el hogar. Habla de herencia, de las raíces que nos sostienen y de lo que transmitimos a quienes vendrán.', invertida: 'Desconexión de las raíces, problemas de herencia, rechazo del legado.' },
]

export function sacarRunas(cantidad: number) {
  const mezcladas = [...RUNAS].sort(() => Math.random() - 0.5)
  return mezcladas.slice(0, cantidad).map(r => ({
    ...r,
    estaInvertida: Math.random() > 0.7,
  }))
}